package sv.edu.udb.www.entities;
// Generated 23-oct-2021 15:09:00 by Hibernate Tools 4.3.1



/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String autor;
     private String editorial;
     private String precio;
     private int existencias;
     private String genero;

    public Libros() {
    }

    public Libros(String codigo, String nombre, String autor, String editorial, String precio, int existencias, String genero) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.autor = autor;
       this.editorial = editorial;
       this.precio = precio;
       this.existencias = existencias;
       this.genero = genero;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public int getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(int existencias) {
        this.existencias = existencias;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }




}


